export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILURE = "USER_SIGNIN_FAILURE";
export const USER_SIGNIN_ERROR = "USER_SIGNIN_ERROR";
export const USER_SIGNOUT = "USER_SIGNOUT";
export const OWNER_SIGNUP = "OWNER_SIGNUP";
export const OWNER_SIGNUP_FAILURE = "OWNER_SIGNUP_FAILURE";
export const CUSTOMER_SIGNUP = "CUSTOMER_SIGNUP";
export const CUSTOMER_SIGNUP_FAILURE = "CUSTOMER_SIGNUP_FAILURE";
export const CUSTOMER_UPDATE_FAILURE = "CUSTOMER_UPDATE_FAILURE";
export const OWNER_UPDATE = "OWNER_UPDATE";
export const OWNER_UPDATE_FAILURE = "OWNER_UPDATE_FAILURE";

export const OWNER_NEW_ORDER = "OWNER_NEW_ORDER";
export const OWNER_NEW_ORDER_FAILURE = "OWNER_NEW_ORDER_FAILURE";

export const OWNER_DELIVERED_ORDER = "OWNER_DELIVERED_ORDER";
export const OWNER_DELIVERED_ORDER_FAILURE = "OWNER_DELIVERED_ORDER_FAILURE";

export const OWNER_CANCELLED_ORDER = "OWNER_CANCELLED_ORDER";
export const OWNER_CANCELLED_ORDER_FAILURE = "OWNER_CANCELLED_ORDER_FAILURE";

export const OWNER_ORDER_UPDATE = "OWNER_ORDER_UPDATE";
export const OWNER_ORDER_UPDATE_FAILURE = "OWNER_ORDER_UPDATE_FAILURE";

export const OWNER_MENU = "OWNER_MENU";
export const OWNER_MENU_FETCH_FAILURE = "OWNER_MENU_FETCH_FAILURE";

export const OWNER_MENU_UPDATE = "OWNER_MENU_UPDATE";
export const OWNER_MENU_UPDATE_FAILURE = "OWNER_MENU_UPDATE_FAILURE";

export const OWNER_MENU_ADD = "OWNER_MENU_ADD";
export const OWNER_MENU_ADD_FAILURE = "OWNER_MENU_ADD_FAILURE";

export const CUSTOMER_UPDATE = "CUSTOMER_UPDATE";
export const CART_ADD = "CART_ADD";
export const LOCATION_UPDATE = "LOCATION_UPDATE";

export const CUSTOMER_ORDERS = "CUSTOMER_ORDERS";
export const CUSTOMER_ORDERS_FAILURE = "CUSTOMER_ORDERS_FAILURE";

export const CUSTOMER_NEWORDER = "CUSTOMER_NEWORDER";
export const CUSTOMER_NEWORDER_FAILURE = "CUSTOMER_NEWORDER_FAILURE";
